//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeignLanguageSchoolLibraryTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupsClients
    {
        public int IdGroupClient { get; set; }
        public int IdGroup { get; set; }
        public int IdClient { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
