//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeignLanguageSchoolApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassesClients
    {
        public int IdClassClient { get; set; }
        public int ClientId { get; set; }
        public int ClassId { get; set; }
        public Nullable<byte> IsClientWasOnClass { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
